### ISSUE TITLE
False negative check

### ISSUE THREAD

**Issue by asvetlov** [sanitizers/chronographer-github-app#17]
PR https://github.com/aio-libs/aiohttp/pull/3955 is marked red: ("Timeline protection: History fragments missing") but it has correct `CHANGES/3551.misc`.

@webknjaz please check what is going wrong?

**Comment by webknjaz** [comment]
It's explained in the details section of https://github.com/aio-libs/aiohttp/runs/183618685:
> No files matching re.compile('CHANGES/(?P<issue_number>[^\./]+)\.(?P<fragment_type>bugfix|doc|feature|removal|trivial|vendor)(\.\d+)?(\.[^\./]+)*$') pattern added

Since 
https://github.com/aio-libs/aiohttp/blob/master/pyproject.toml doesn't list the fragment types, the bot falls back to a hard-coded list defined here:
https://github.com/sanitizers/chronographer-github-app/blob/0a112ca/chronographer/event_handlers.py#L258-L265

**Comment by webknjaz** [comment]
When the config has clearly defined types, the bot uses those for checking fragments. Here's a few examples:

- https://github.com/tox-dev/tox/blob/94436c3/pyproject.toml#L21-L49 
- https://github.com/pypa/pip/blob/82dbcda/pyproject.toml#L13-L46

**Comment by webknjaz** [comment]
Maybe I could use https://github.com/hawkowl/towncrier/blob/ecd438c/src/towncrier/_settings.py#L13-L21 to identify defaults in a more stable way.
