### ISSUE TITLE
Rename the check to "Chronographer"

### ISSUE THREAD

**Issue by pradyunsg** [sanitizers/chronographer-github-app#18]
Currently:

- The check is named "Timeline protection"
- The description begins with "Timeline protection: "

![Screenshot 2020-01-01 at 4 30 55 PM](https://user-images.githubusercontent.com/3275593/71640653-1a961400-2cb4-11ea-8409-3a74849fcc21.png)

Suggestion:

- Rename the check to "Chronographer"
  - More direct association with the GitHub App that was installed.
- Drop "Timeline protection: " prefix from the description.
  - Redundancy, since the job of the Chronographer is pretty clear. :)

**Comment by webknjaz** [comment]
> Drop "Timeline protection: " prefix from the description.

This one is pretty straightforward. Feel free to send a PR.
I think there's only 3 tiny changes to be made here:
https://github.com/sanitizers/chronographer-github-app/blob/5119914/chronographer/event_handlers.py#L137 / https://github.com/sanitizers/chronographer-github-app/blob/5119914/chronographer/event_handlers.py#L237 / https://github.com/sanitizers/chronographer-github-app/blob/5119914/chronographer/event_handlers.py#L250


> Rename the check to "Chronographer"

I was thinking along the lines of eventually adding a check that would show the compiled notes. So I'm not so sure about this. I was also thinking that it may be useful to make this changeable via a config.

Also, it probably makes sense to reinvent the terminology because it confuses folks. Maybe we could collect some further ideas before doing any changes here?

**Comment by webknjaz** [comment]
@pradyunsg I think, this is addressed with https://github.com/sanitizers/chronographer-github-app/commit/afa408d44d83726030cb699ec0c0c48169cd155e and https://github.com/sanitizers/chronographer-github-app/commit/d36ea77d8ed0f622e4e149ff9097fbff999ee1a6.

WDYT? Close if you agree.
